services:
  livekit-server:
    container_name: livekit-server
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
    volumes:
      - ./config.yaml:/config.yaml
    command: --config /config.yaml
    environment:
      - CONFIG_FILE=/config.yaml
      - LIVEKIT_API_KEY=108cc770f923cf669912dfed679c73c3
      - LIVEKIT_API_SECRET=2c0c06d6975ee23e9ae32460ff0599b4

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      AWS_SDK_LOAD_CONFIG: "1"
    volumes:
      - /home/ganesh/.aws:/root/.aws:ro # Ensure correct mounting of AWS credentials
      #- C:\Users\Vikas\.aws:/root/.aws:ro# Ensure correct mounting of AWS credentials
      
  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    volumes:
      - ./coturn.conf:/etc/turnserver.conf
    command: ["turnserver", "-c", "/etc/turnserver.conf"]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Best to use read-only mode
    depends_on:
      - livekit-server
  
networks:
  default:
    name: livekit_network
