services:

  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      AWS_SDK_LOAD_CONFIG: "1"
    volumes:
      - /home/ubuntu/.aws:/root/.aws:ro # This ensures the .aws directory is mounted correctly

volumes:
  redis_data:
    driver: local # Define the redis_data volume for persistent storage
