version: '3.8'

services:
  livekit-server:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    volumes:
      - ./livekit-config.yaml:/config.yaml
    command: --config /config.yaml
    environment:
      - LIVEKIT_API_KEY=108cc770f923cf669912dfed679c73c3
      - LIVEKIT_API_SECRET=2c0c06d6975ee23e9ae32460ff0599b4
    ports:
      - "7880:7880"
      - "7881:7881"
      - "5000-5200:5000-5200/udp"
    depends_on:
      - redis

  redis:
    image: redis  
    container_name: redis
    ports:
      - "6379:6379"

  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    volumes:
      - ./coturn.conf:/etc/turnserver.conf
    ports:
      - "3478:3478"
      - "49152-65535:49152-65535/udp"

  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - livekit-server
