services:
  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "0.0.0.0:6379:6379"  # Expose Redis on all network interfaces for external access
    volumes:
      - ./redis.conf:/etc/redis/redis.conf  # Mount local redis.conf
      - redis_data:/data  # Persistent data storage
    command: ["redis-server", "/etc/redis/redis.conf"]  # Use custom config

  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    volumes:
      - ./coturn.conf:/etc/turnserver.conf
    command: ["turnserver", "-c", "/etc/turnserver.conf"]

  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    volumes:
  - ~/.aws:/root/.aws

volumes:
  redis_data:
    driver: local # Define the redis_data volume for persistent storage