services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      AWS_SDK_LOAD_CONFIG: "1"
    volumes:
      - /home/ubuntu/.aws:/root/.aws:ro # Ensure correct mounting of AWS credentials

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Best to use read-only mode
    depends_on:
      - app
  
